name: challenge_bento
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cherry_toast: ^1.11.0
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.1+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  go_router: ^14.2.3
  intl: ^0.19.0
  mobx: ^2.3.3+2
  mobx_codegen: ^2.6.1
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  coverage: ^1.9.0
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - database/data.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/challenge-bento-icon.png"
  adaptive_icon_background: "#FFFFFF"

