// Mocks generated by Mockito 5.4.4 from annotations
// in challenge_bento/test/app/modules/item_detail/item_detail_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:challenge_bento/app/core/models/models.dart' as _i4;
import 'package:challenge_bento/app/core/services/product/product_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i2.ProductService {
  @override
  _i3.Future<_i4.ProductModel?> getProductById({required int? productId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [],
          {#productId: productId},
        ),
        returnValue: _i3.Future<_i4.ProductModel?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.ProductModel?>.value(),
      ) as _i3.Future<_i4.ProductModel?>);
}
