// Mocks generated by Mockito 5.4.4 from annotations
// in challenge_bento/test/app/core/services/todays_special/todays_special_service_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:challenge_bento/app/core/models/models.dart' as _i5;
import 'package:challenge_bento/app/core/repositories/repositories.dart' as _i2;
import 'package:challenge_bento/app/core/services/services.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodaysSpecialRepository_0 extends _i1.SmartFake
    implements _i2.TodaysSpecialRepository {
  _FakeTodaysSpecialRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodaysSpecialServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodaysSpecialServiceImpl extends _i1.Mock
    implements _i3.TodaysSpecialServiceImpl {
  @override
  _i2.TodaysSpecialRepository get todaysSpecialRepository =>
      (super.noSuchMethod(
        Invocation.getter(#todaysSpecialRepository),
        returnValue: _FakeTodaysSpecialRepository_0(
          this,
          Invocation.getter(#todaysSpecialRepository),
        ),
        returnValueForMissingStub: _FakeTodaysSpecialRepository_0(
          this,
          Invocation.getter(#todaysSpecialRepository),
        ),
      ) as _i2.TodaysSpecialRepository);

  @override
  _i4.Future<List<_i5.TodaysSpecialModel>> getAllTodaysSpecials() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllTodaysSpecials,
          [],
        ),
        returnValue: _i4.Future<List<_i5.TodaysSpecialModel>>.value(
            <_i5.TodaysSpecialModel>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.TodaysSpecialModel>>.value(
                <_i5.TodaysSpecialModel>[]),
      ) as _i4.Future<List<_i5.TodaysSpecialModel>>);
}
